//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orc.SupportPackage.Xaml.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orc.SupportPackage.Xaml.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create support package for {0}.
        /// </summary>
        internal static string SupportPackage_CreateSupportPackage {
            get {
                return ResourceManager.GetString("SupportPackage_CreateSupportPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can create a support package. The support package will contain information that might help support engineers to analyze any possible issues..
        /// </summary>
        internal static string SupportPackage_Explanation_01 {
            get {
                return ResourceManager.GetString("SupportPackage_Explanation_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depending on the amount of information to gather, this operation can take several seconds to a few minutes. Please be patient while the support package is being created..
        /// </summary>
        internal static string SupportPackage_Explanation_02 {
            get {
                return ResourceManager.GetString("SupportPackage_Explanation_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note that support packages might contain sensitive information so make sure you only share this information with a support engineer..
        /// </summary>
        internal static string SupportPackage_Explanation_03 {
            get {
                return ResourceManager.GetString("SupportPackage_Explanation_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I understand, create the support package.
        /// </summary>
        internal static string SupportPackage_IUnderstandCreateSupportPackage {
            get {
                return ResourceManager.GetString("SupportPackage_IUnderstandCreateSupportPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open directory.
        /// </summary>
        internal static string SupportPackage_OpenDirectory {
            get {
                return ResourceManager.GetString("SupportPackage_OpenDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support package files.
        /// </summary>
        internal static string SupportPackage_SupportPackageFiles {
            get {
                return ResourceManager.GetString("SupportPackage_SupportPackageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration files.
        /// </summary>
        internal static string SupportPackage_SupportPackageFileType_ConfigurationFiles_Title {
            get {
                return ResourceManager.GetString("SupportPackage_SupportPackageFileType_ConfigurationFiles_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable files.
        /// </summary>
        internal static string SupportPackage_SupportPackageFileType_ExecutableFiles_Title {
            get {
                return ResourceManager.GetString("SupportPackage_SupportPackageFileType_ExecutableFiles_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image files.
        /// </summary>
        internal static string SupportPackage_SupportPackageFileType_ImageFiles_Title {
            get {
                return ResourceManager.GetString("SupportPackage_SupportPackageFileType_ImageFiles_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log files.
        /// </summary>
        internal static string SupportPackage_SupportPackageFileType_LogFiles_Title {
            get {
                return ResourceManager.GetString("SupportPackage_SupportPackageFileType_LogFiles_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System information.
        /// </summary>
        internal static string SupportPackage_SupportPackageFileType_SystemInformation_Title {
            get {
                return ResourceManager.GetString("SupportPackage_SupportPackageFileType_SystemInformation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text files.
        /// </summary>
        internal static string SupportPackage_SupportPackageFileType_TextFiles_Title {
            get {
                return ResourceManager.GetString("SupportPackage_SupportPackageFileType_TextFiles_Title", resourceCulture);
            }
        }
    }
}
